spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      host: ${PARK_TECH_MONGODB_HOST:"localhost"}
      port: ${PARK_TECH_MONGODB_PORT:27017}
      database: ${PARK_TECH_MONGODB_DATABASE:parktech}
      username: ${PARK_TECH_MONGODB_USERNAME:parktech}
      password: ${PARK_TECH_MONGODB_PASSWORD:parktech}
      authentication-database : ${PARK_TECH_MONGODB_AUTHENTICATION_DATABASE:admin}


  docker:
    compose:
      enabled: true
      file: docker-parktech-dev/docker-compose.yaml


logging:
  pattern:
    console: "%d{ABSOLUTE_MICROS} [%-5level] [%t] %c{1} - %msg%n"

  level:
    br:
      com:
        fsales: debug

