spring:
  application:
    name: @project.name@
    description: @project.version@
    version: @project.description@

  data:
    mongodb:
      auto-index-creation: true

  docker:
    compose:
      enabled: false

  profiles:
    active: ${PARK_TECH_PROFILE_ENVIRONMENT:}


springdoc:
  show-actuator: true
  api-docs:
    groups:
      enabled: true



logging:
  pattern:
    console: "%d{ABSOLUTE_MICROS} [%-5level] [%t] %c{1} - %msg%n"
  level:
    br:
      com:
        fsales: info
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

server:
  error:
    include-stacktrace: never # desabilitar stacktrace no json que e retornado em caso de erro
  port: 8080

##
application:
  title: '@project.name@'
  version: '@project.version@'

  swagger:
    application:
      name: '@project.name@'
      description: '@project.description@'
      version: '@project.version@'

  client:
    endereco:
      host: https://viacep.com.br/ws