spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      uri: ${PARK_TECH_MONGODB_URI}
      database: ${PARK_TECH_MONGODB_DATABASE}
      authentication-database : ${PARK_TECH_MONGODB_AUTHENTICATION_DATABASE:admin}

  docker:
    compose:
      enabled: true
      file: docker-parktech-dev/docker-compose.yaml


logging:
  pattern:
    console: "%d{ABSOLUTE_MICROS} [%-5level] [%t] %c{1} - %msg%n"

  level:
    br:
      com:
        fsales: debug

