spring:
  config:
    activate:
      on-profile: dev

  docker:
    compose:
      enabled: true


logging:
  pattern:
    console: "%d{ABSOLUTE_MICROS} [%-5level] [%t] %c{1} - %msg%n"

  level:
    br:
      com:
        fsales: debug

