version: "3.8"

services:
  mongo:
    container_name: mongodb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: parktech
      MONGO_USERS: '[{"username": "parktech", "password": "parktech", "roles": ["readWrite", "dbAdmin"]}]'
    restart: always
    ports:
      - 27017:27017
    networks:
      - spring-docker-compose-dev

  mongo-express:
    container_name: mongo-express-park-tech
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: parktech
      ME_CONFIG_BASICAUTH_PASSWORD: parktech
      ME_CONFIG_MONGODB_URL: mongodb://parktech:parktech@mongo:27017/parktech
      ME_CONFIG_MONGODB_ENABLE_SCHEME_NOTRECOGNIZED: "false"
      ME_CONFIG_MONGODB_AUTH_MECHANISM: SCRAM-SHA-256
    ports:
      - 8081:8081
    networks:
      - spring-docker-compose-dev

networks:
  spring-docker-compose-dev:
