name: Terraform Deployment - AWS

on:
  push:
    branches:
      - deploy-aws-terraform

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:

    name: Terraform Deployment - AWS
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/env/hmg
        shell: bash
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Get Docker Hub Image Tag
        id: get_image_tag
        run: |
          TAG_IMAGE=$(curl -s "https://registry.hub.docker.com/v2/repositories/fosales/park-tech/tags/" | \
            jq -r '.results | sort_by(.last_updated) | last(.[]).name')
          echo "Latest Docker Hub Image Tag: $TAG_IMAGE"
          echo "TAG_IMAGE=$TAG_IMAGE" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set SSL verification to false
        run: git config --global http.sslVerify false

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Terraform init
        run: |
          echo "** Running Terraform Init**"
          
          export TF_VAR_uriDatabase=$URI_DATABASE
          export TF_VAR_imagemTag=$TAG_IMAGE

          terraform init

        env:
          URI_DATABASE: ${{secrets.URI_DATABASE}}
          TAG_IMAGE: ${{env.TAG_IMAGE}}

      - name: Plan Terraform changes
        run: |
          echo "** Running Terraform Plan**"
          
          export TF_VAR_uriDatabase=$URI_DATABASE
          export TF_VAR_imagemTag=$TAG_IMAGE
          
          terraform plan -input=false -out=tfplan

        env:
          URI_DATABASE: ${{secrets.URI_DATABASE}}
          TAG_IMAGE: ${{env.TAG_IMAGE}}

      - name: Terraform Apply
        run: |
          echo "** Running Terraform Apply**"
          
          export TF_VAR_uriDatabase=$URI_DATABASE
          export TF_VAR_imagemTag=$TAG_IMAGE
          
          terraform apply -auto-approve -input=false tfplan
        env:
          URI_DATABASE: ${{secrets.URI_DATABASE}}
          TAG_IMAGE: ${{env.TAG_IMAGE}}
