name: Publish Image Registry - Branch Develop

on:
  pull_request:
    types:
      - closed
    paths:
      - 'park-tech/**'

env:

  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/park-tech

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  #  github-context:
  #    if: |
  #      github.event_name == 'pull_request' &&
  #      contains(github.event.pull_request.base.ref, 'develop') &&
  #      contains(github.event.pull_request.head.ref, 'feature/') &&
  #      github.event.pull_request.merged == true
  #
  #    name: job-context
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Dump GitHub context
  #        env:
  #          GITHUB_CONTEXT: ${{ toJSON(github) }}
  #        run: echo "$GITHUB_CONTEXT"

  publish-image-registry:
    if: |
      github.event_name == 'pull_request' &&
      contains(github.event.pull_request.base.ref, 'develop') &&
      contains(github.event.pull_request.head.ref, 'feature/') &&
      github.event.pull_request.merged == true

    #    needs: [github-context]

    name: Publish image docker registry
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ''

    # permissão
    permissions:
      contents: read
      packages: write

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: park-tech
        shell: bash
    steps:

      - name: "Check out the repo"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: Set execute permissions for mvnw
        run: chmod +x mvnw

      - name: Set Release version env variable
        run: |
          echo "IMAGE_TAG=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout).${{github.run_number}}" >> $GITHUB_ENV

      - name: "docker login"
        uses: "docker/login-action@v2"
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./park-tech
          file: ./park-tech/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}